// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Richedit;

{ITE} {DFMFileType} {REABOUT.dfm}
{ITE} {DFMFileType} {REMain.dfm}
{ITE} {RCFileType} {Richedit_DRC.rc}

{$R 'REABOUT.dfm' AboutBox:TForm}
{$R 'REMain.dfm' MainForm:TForm}
{$R 'Richedit_DRC.res' 'Richedit_DRC.rc'}

{$E FRA}

begin
end.