{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 1995-2018 Embarcadero Technologies, Inc. }
{              All rights reserved                      }
{                                                       }
{*******************************************************}

type
  iconv_t = Pointer;
  {$EXTERNALSYM iconv_t}
  Piconv_t = ^iconv_t;
